#!/bin/sh
set -eu

: "${CLOUD_PROVIDER:=volcengine}"
: "${AGENTKIT_CLOUD_PROVIDER:=${CLOUD_PROVIDER}}"
: "${VOLCENGINE_AGENTKIT_HOST:=top.vestack.cloud}"
: "${VOLCENGINE_AGENTKIT_SCHEME:=http}"
: "${VOLCENGINE_AGENTKIT_REGION:=cn-bj}"
: "${VOLCENGINE_AGENTKIT_SERVICE:=agentkit}"
: "${VEADK_STUDIO_AUTH_MODE:=gateway}"
: "${VEADK_STUDIO_LISTEN_PORT:=${_FAAS_RUNTIME_PORT:-8000}}"

export CLOUD_PROVIDER AGENTKIT_CLOUD_PROVIDER
export VOLCENGINE_AGENTKIT_HOST VOLCENGINE_AGENTKIT_SCHEME
export VOLCENGINE_AGENTKIT_REGION VOLCENGINE_AGENTKIT_SERVICE

exec python -m veadk.cli.cli studio \
  --provider "${CLOUD_PROVIDER}" \
  --auth-mode "${VEADK_STUDIO_AUTH_MODE}" \
  --host 0.0.0.0 \
  --port "${VEADK_STUDIO_LISTEN_PORT}"
