# Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""IAM policies for the VeFaaS-hosted frontend (`veadk studio deploy`).

The deployed function assumes this role (trust principal ``vefaas``) and reads
its STS credentials from the injected credential file, so the frontend's
``/web/*`` endpoints can manage AgentKit runtimes on the user's behalf. The
document grants the union of permissions the frontend + AgentKit deploy/runtime
flows exercise (agentkit, vefaas, cr, cp, tos, iam, ark, identity, vikingdb, …).
"""

FRONTEND_DEPLOY_SYSTEM_POLICIES: tuple[str, ...] = (
    "ArkReadOnlyAccess",
    "TLSReadOnlyAccess",
    "APMPlusServerReadOnlyAccess",
    "VikingdbReadOnlyAccess",
    "ESCloudReadOnlyAccess",
    "LLMShieldProtectSdkAccess",
    "TorchlightApiFullAccess",
    "Mem0ReadOnlyAccess",
    "IDReadOnlyAccess",
    "TagFullAccess",
)

# The trust relationship that lets a VeFaaS function assume the role.
FRONTEND_DEPLOY_TRUST_POLICY: dict = {
    "Statement": [
        {
            "Effect": "Allow",
            "Action": ["sts:AssumeRole"],
            "Principal": {"Service": ["vefaas"]},
        }
    ]
}

# The permission policy attached to the role (provided by the platform team).
FRONTEND_DEPLOY_POLICY: dict = {
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "agentkit:*",
                "apmplus_server:Get*",
                "apmplus_server:List*",
                "Volc_Observe:Get*",
                "Volc_Observe:*Describe*",
                "Volc_Observe:*List*",
                "cloudmonitor:Get*",
                "cloudmonitor:*Describe*",
                "cloudmonitor:*List*",
                "tls:Get*",
                "tls:Describe*",
                "tls:List*",
                "tag:TagResources",
                "tag:UntagResources",
                "apig:ConvertMcpConfig",
                "apmplus_server:CreateOrder",
                "ark:CreateApiKey",
                "ark:GetEndpoint",
                "ark:GetRawApiKey",
                "ark:InnerDescribeModelEndpoints",
                "ark:ListApiKeys",
                "ark:ListEndpoints",
                "ark:ListFoundationModelVersions",
                "ark:ListModelActivations",
                "ark:ListModelChargeItems",
                "ark:OpenModelChargeItem",
                "ark:ListFoundationModels",
                "content_customization:GetQuickOpenSearchInfo",
                "cp:CreatePipeline",
                "cp:CreateWorkspace",
                "cp:DeletePipeline",
                "cp:GetDefaultWorkspaceInner",
                "cp:GetInstance",
                "cp:GetTaskRunLog",
                "cp:GetTaskRunLogDownloadURI",
                "cp:ListPipelineRuns",
                "cp:ListPipelineRunStagesInner",
                "cp:ListPipelines",
                "cp:ListWorkspaces",
                "cp:RunPipeline",
                "cr:AddVpcEndpointLinkedVpc",
                "cr:CreateEndpointAclPolicies",
                "cr:CreateNamespace",
                "cr:CreateRegistry",
                "cr:CreateRepository",
                "cr:DeleteEndpointAclPolicies",
                "cr:DeleteNamespace",
                "cr:DeleteRegistry",
                "cr:DeleteTags",
                "cr:GetAuthorizationToken",
                "cr:GetPublicEndpoint",
                "cr:GetVpcEndpoint",
                "cr:ListDomains",
                "cr:ListNamespaces",
                "cr:ListRegistries",
                "cr:ListRepositories",
                "cr:ListTags",
                "cr:RemoveVpcEndpointLinkedVpc",
                "cr:StartRegistry",
                "cr:UpdateNamespace",
                "cr:UpdatePublicEndpoint",
                "cr:UpdateVpcEndpoint",
                "ESCloud:GetMLApiKey",
                "ESCloud:GetScene",
                "ESCloud:GetSceneInstance",
                "ESCloud:ListMLApiKeys",
                "iam:AttachRolePolicy",
                "iam:CheckServiceLinkedRole",
                "iam:CreateRole",
                "iam:CreateServiceLinkedRole",
                "iam:DeleteRole",
                "iam:DetachRolePolicy",
                "iam:GetPolicy",
                "iam:GetRole",
                "iam:GetServiceLinkedRoleTemplate",
                "iam:GetUser",
                "iam:ListProjects",
                "iam:ListRoles",
                "iam:ListUsers",
                "iam:UpdateRole",
                "iam:ListAttachedRolePolicies",
                "id:CreateApiKey",
                "id:CreateApiKeyCredentialProvider",
                "id:CreateInboundAuthConfig",
                "id:CreateGroup",
                "id:DeleteApiKey",
                "id:DeleteInboundAuthConfig",
                "id:GetCallerIdentity",
                "id:GetInboundAuthConfig",
                "id:GetResourceApiKey",
                "id:GetTenantServiceStatus",
                "id:GetUserPool",
                "id:GetUser",
                "id:ListUsers",
                "id:ListGroups",
                "id:UpdateGroup",
                "id:AddUsersToGroup",
                "id:RemoveUsersFromGroup",
                "id:GetUserPoolClient",
                "id:ListCredentialProviders",
                "id:ListNamespaces",
                "id:ListServices",
                "id:ListUserPoolClients",
                "id:ListUserPools",
                "id:UpdateInboundAuthConfig",
                "location:DescribeRegions",
                "mem0:CreateMemoryProject",
                "mem0:DeleteMemoryProject",
                "mem0:DescribeAPIKeyDetail",
                "mem0:DescribeMemoryProjectDetail",
                "mem0:DescribeMemoryProjects",
                "mem0:ModifyMemoryProjectLongTermStrategy",
                "mem0:SearchMemory",
                "mem0:SearchMemoryAllInfo",
                "ml_platform:GetKnowledgeBaseServiceInfo",
                "ml_platform:ListCollections",
                "sts:AssumeRole",
                "tls:ActiveTlsAccount",
                "tls:SearchLogs",
                "tos:CopyObject",
                "tos:CreateBucket",
                "tos:DeleteBucket",
                "tos:DeleteObject",
                "tos:GetAccountStatus",
                "tos:GetBucketInfo",
                "tos:GetObject",
                "tos:HeadBucket",
                "tos:HeadObject",
                "tos:ListBucket",
                "tos:ListBuckets",
                "tos:ListObjects",
                "tos:ListObjectsV2",
                "tos:PostObject",
                "tos:PutObject",
                "vefaas:CreateFunction",
                "vefaas:CreateSandbox",
                "vefaas:CodeUploadCallback",
                "vefaas:CreateDependencyInstallTask",
                "vefaas:DeleteFunction",
                "vefaas:CreateTimer",
                "vefaas:DescribeSandbox",
                "vefaas:EnableUserCrVpcTunnel",
                "vefaas:GetAvailabilityZones",
                "vefaas:GetCodeUploadAddress",
                "vefaas:GetApplication",
                "vefaas:GetApplicationRevisionLog",
                "vefaas:GetDependencyInstallTaskLogDownloadURI",
                "vefaas:GetDependencyInstallTaskStatus",
                "vefaas:GetFunction",
                "vefaas:GetImageConfig",
                "vefaas:GetImageSyncStatus",
                "vefaas:GetReleaseStatus",
                "vefaas:KillSandbox",
                "vefaas:ListFunctions",
                "vefaas:ListRuntimes",
                "vefaas:ListSandboxes",
                "vefaas:ListTriggers",
                "vefaas:QueryUserCrVpcTunnel",
                "vefaas:Release",
                "vefaas:ReleaseApplication",
                "vefaas:SetSandboxTimeout",
                "vefaas:UpdateTimer",
                "vefaas:UpdateFunction",
                "vefaas:UpdateFunctionResource",
                "vikingdb:GetKnowledgeBaseServiceInfo",
                "vikingdb:GetMemorydbInstanceDetail",
                "vikingdb:ListCollections",
                "vikingdb:MemoryCollectionInfo",
                "vikingdb:MemoryCollectionList",
                "vikingdb:MemorySearch",
                "vikingdb:MemorySearchUser",
                "vikingdb:GetCollectionInfo",
                "vikingdb:CreateCollection",
                "vikingdb:CreateKnowledgedbInstance",
                "vikingdb:GetKnowledgedbInstanceStatus",
                "vikingdb:AddDocument",
                "vikingdb:UpdateCollection",
                "vikingdb:DeleteCollection",
                "vikingdb:CreateMemorydbInstance",
                "vpc:DescribeSecurityGroups",
                "vpc:DescribeSubnets",
                "vpc:DescribeVpcAttributes",
                "vpc:DescribeVpcs",
                "vke:ListClusters",
                "vke:ForwardKubernetesApi",
                "vke:ListServices",
                "ecs:DescribeInstances",
                "llmshield:ListInstances",
                "llmshield:ListApps",
                "llmshield:CreateOuterApp",
                "ark:ListSubscribeTrade",
                "ark:EstimateSubscribePrice",
                "ark:CreateSubscribeTrade",
                "ark:GetCodingPlanUsage",
                "rds_mysql:DescribeDBInstances",
                "rds_mysql:DescribeDBInstanceEndpoints",
                "rds_mysql:DescribeDBAccounts",
                "rds_mysql:DescribeDatabases",
                "rds_postgresql:DescribeDBInstances",
                "rds_postgresql:DescribeDBAccounts",
                "rds_postgresql:DescribeDatabases",
                "aidap:DescribeWorkspaces",
                "aidap:DescribeBranches",
                "aidap:DescribeComputes",
                "aidap:DescribeDBAccounts",
                "aidap:DescribeDatabases",
            ],
            "Resource": ["*"],
        }
    ]
}
